<template>
  <div class="study-report">
    <div class="report-controls no-print">
      <button class="print-btn" @click="printReport">Print Report</button>
      <button class="back-btn" @click="goBack">Back</button>
    </div>

    <div class="report-content">
      <div class="report-header">
        <h1 class="report-title">Ninja Flashcards Study Progress Report</h1>
        <div class="report-info">
          <p><strong>User:</strong> {{ $store.state.user.username }}</p>
          <p><strong>Generated:</strong> {{ currentDateTime }}</p>
          <p><strong>Total Decks Studied:</strong> {{ reportData.length }}</p>
        </div>
      </div>

      <div v-if="isLoading" class="loading">
        <ninja-loader/>
      </div>

      <div v-else class="report-table-container">
        <table class="report-table">
          <thead>
            <tr>
              <th>Deck Name</th>
              <th>Genre/Subject</th>
              <th>Score</th>
              <th>Performance</th>
              <th>Last Studied</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(record, index) in reportData" :key="index" :class="getRowClass(record.performance)">
              <td class="deck-name">{{ record.deck_name }}</td>

              <td>{{ record.genre }}</td>

              <td class="center">{{ getScoreDisplay(record) }}</td>

              <td class="center">
                <span class="brain-color" :class="getBrainColorClass(record.score)">
                  {{ getBrainColorText(record.score) }}
                </span>
              </td>

              <td class="center">{{ formatDateTime(record.last_updated) }}</td>
            </tr>
          </tbody>
        </table>

        <div class="report-summary">
          <h3>Study Summary</h3>
          <div class="summary-stats">
            <div class="stat-item">
              <span class="stat-label">Average Score:</span>
              <span class="stat-value">{{ averageScore }}/3</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Excellent Performance:</span>
              <span class="stat-value">{{ excellentCount }} decks</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Good Performance:</span>
              <span class="stat-value">{{ goodCount }} decks</span>
            </div>
            <div class="stat-item">
              <span class="stat-label">Needs Improvement:</span>
              <span class="stat-value">{{ poorCount }} decks</span>
            </div>
          </div>
        </div>
      </div>

      <div class="report-footer">
        <p>Report generated by Ninja Flashcards Application</p>
        <p>Study consistently to improve your performance!</p>
      </div>
    </div>
  </div>
</template>

<script>
import DeckService from '@/services/DeckService.js'
import NinjaLoader from '../components/NinjaLoader.vue'

export default {
  name: "study-report",
  components: {
    NinjaLoader
  },
  data() {
    return {
      reportData: [],
      isLoading: true,
      currentDateTime: new Date().toLocaleString()
    }
  },
  computed: {
    averageScore() {
      if (this.reportData.length === 0) return 0;
      const total = this.reportData.reduce((sum, record) => sum + record.score, 0);
      return (total / this.reportData.length).toFixed(1);
    },
    excellentCount() {
      return this.reportData.filter(record => record.performance === 'Excellent').length;
    },
    goodCount() {
      return this.reportData.filter(record => record.performance === 'Good').length;
    },
    poorCount() {
      return this.reportData.filter(record => record.performance === 'Poor').length;
    }
  },
  methods: {
    printReport() {
      window.print();
    },
    goBack() {
      this.$router.go(-1);
    },
    getRowClass(performance) {
      return `row-${performance.toLowerCase()}`;
    },
    getStatusClass(status) {
      switch(status) {
        case 1: return 'private';
        case 2: return 'unlisted';
        case 3: return 'public';
        default: return '';
      }
    },
    getStatusText(status) {
      switch(status) {
        case 1: return 'Private';
        case 2: return 'Unlisted';  
        case 3: return 'Public';
        default: return 'Unknown';
      }
    },
    formatDate(dateString) {
      if (!dateString) return 'Never';
      return new Date(dateString).toLocaleDateString();
    },
    formatDateTime(dateString) {
      if (!dateString) return 'Never';
      const date = new Date(dateString);
      const dateStr = date.toLocaleDateString();
      const timeStr = date.toLocaleTimeString();
      return `${dateStr} ${timeStr}`;
    },
    getPerformance(score) {
      switch(score) {
        case 3: return 'Excellent';
        case 2: return 'Good';
        case 1: return 'Poor';
        default: return 'No Data';
      }
    },
    getScoreText(score) {
      switch(score) {
        case 3: return 'Green';
        case 2: return 'Yellow';
        case 1: return 'Red';
        default: return 'No Data';
      }
    },
    getScoreDisplay(record) {
      // Use actual correct answers from database if available, otherwise estimate
      if (record.correct_answers !== undefined && record.num_cards !== undefined) {
        return `(${record.correct_answers}/${record.num_cards})`;
      }
      const totalCards = record.num_cards || record.card_count || 0;
      if (totalCards > 0) {
        const correct = Math.round((this.getScorePercentage(record.score) / 100) * totalCards);
        return `(${correct}/${totalCards})`;
      }
      return this.getBrainColorText(record.score);
    },
    getScorePercentage(score) {
      switch(score) {
        case 3: return 85; // Green = ~85%
        case 2: return 65; // Yellow = ~65%
        case 1: return 35; // Red = ~35%
        default: return 0;
      }
    },
    getBrainColorText(score) {
      switch(score) {
        case 3: return '🟢 Green';
        case 2: return '🟡 Yellow';
        case 1: return '🔴 Red';
        default: return 'No Data';
      }
    },
    getBrainColorClass(score) {
      switch(score) {
        case 3: return 'green';
        case 2: return 'yellow';
        case 1: return 'red';
        default: return '';
      }
    },
    async loadReportData() {
      try {
        // Get user's studied decks with history
        const response = await DeckService.getUserStudyReport(this.$store.state.user.id);
        this.reportData = response.data.map(record => ({
          ...record,
          performance: this.getPerformance(record.score)
        }));
        
        setTimeout(() => {
          this.isLoading = false;
        }, 800);
      } catch (error) {
        // eslint-disable-next-line no-console
        console.error('Error loading report data:', error);
        this.isLoading = false;
      }
    }
  },
  created() {
    this.loadReportData();
  }
};
</script>

<style scoped>
.no-print {
  display: block;
}

.report-controls {
  margin-bottom: 20px;
  text-align: center;
}

.print-btn, .back-btn {
  margin: 0 10px;
  padding: 10px 20px;
  font-size: 16px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.print-btn {
  background-color: #4CAF50;
  color: white;
}

.print-btn:hover {
  background-color: #45a049;
}

.back-btn {
  background-color: #f44336;
  color: white;
}

.back-btn:hover {
  background-color: #da190b;
}

.report-content {
  max-width: 1000px;
  margin: 0 auto;
  background: white;
  padding: 30px;
  box-shadow: 0 0 10px rgba(0,0,0,0.1);
}

.report-header {
  text-align: center;
  margin-bottom: 30px;
  border-bottom: 2px solid #333;
  padding-bottom: 20px;
}

.report-title {
  color: #333;
  font-size: 28px;
  margin-bottom: 15px;
}

.report-info {
  display: flex;
  justify-content: space-around;
  margin-top: 15px;
}

.report-info p {
  margin: 5px;
  color: #666;
}

.report-table-container {
  margin: 30px 0;
}

.report-table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 30px;
}

.report-table th,
.report-table td {
  border: 1px solid #ddd;
  padding: 12px;
  text-align: left;
}

.report-table th {
  background-color: #f8f9fa;
  font-weight: bold;
  color: #333;
}

.report-table .center {
  text-align: center;
}

.deck-name {
  font-weight: bold;
}

.row-excellent {
  background-color: #d4edda;
}

.row-good {
  background-color: #fff3cd;
}

.row-poor {
  background-color: #f8d7da;
}

.performance-badge, .status-badge, .brain-color {
  padding: 4px 8px;
  border-radius: 12px;
  font-size: 12px;
  font-weight: bold;
}

.performance-badge.excellent {
  background-color: #28a745;
  color: white;
}

.performance-badge.good {
  background-color: #ffc107;
  color: #212529;
}

.performance-badge.poor {
  background-color: #dc3545;
  color: white;
}

.status-badge.private {
  background-color: #6c757d;
  color: white;
}

.status-badge.unlisted {
  background-color: #17a2b8;
  color: white;
}

.status-badge.public {
  background-color: #28a745;
  color: white;
}

.brain-color.green {
  background-color: #28a745;
  color: white;
}

.brain-color.yellow {
  background-color: #ffc107;
  color: #212529;
}

.brain-color.red {
  background-color: #dc3545;
  color: white;
}

.report-summary {
  margin-top: 40px;
  padding: 20px;
  background-color: #f8f9fa;
  border-radius: 5px;
}

.report-summary h3 {
  margin-bottom: 15px;
  color: #333;
}

.summary-stats {
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
}

.stat-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 10px;
}

.stat-label {
  font-weight: bold;
  color: #666;
  margin-bottom: 5px;
}

.stat-value {
  font-size: 24px;
  font-weight: bold;
  color: #333;
}

.report-footer {
  margin-top: 40px;
  text-align: center;
  border-top: 1px solid #ddd;
  padding-top: 20px;
  color: #666;
}

@media print {
  .no-print {
    display: none !important;
  }
  
  .report-content {
    box-shadow: none;
    margin: 0;
    padding: 20px;
  }
  
  .report-table {
    font-size: 12px;
  }
  
  .report-table th,
  .report-table td {
    padding: 8px;
  }
  
  .report-title {
    font-size: 24px;
  }
  
  .report-info {
    flex-direction: column;
    align-items: center;
  }
  
  .summary-stats {
    flex-direction: column;
    align-items: center;
  }
  
  .stat-item {
    margin: 5px 0;
  }
  
  .report-header {
    page-break-after: avoid;
  }
  
  .report-table {
    page-break-inside: avoid;
  }
  
  .report-summary {
    page-break-before: avoid;
  }
}

.loading {
  text-align: center;
  padding: 50px;
}
</style>